name: hello-cake-meetup

variables:
  artifactsRootDir: $(System.DefaultWorkingDirectory)/.artifacts

trigger:
  branches:
    include:
      - master
      - preview/*
      - stable/*

stages:
- stage: windows_build
  displayName: Windows
  jobs:
    - job: build_agent
      displayName: Windows Agent
      pool:
        vmImage: vs2017-win2016
            
      steps:
        # Clean and checkout
        - checkout: self
          clean: all
          continueOnError: 'false'

        # Build, test and generate artifact output
        - powershell: .\build.ps1
          displayName: 'Build, test and generate artifact output on working directory'
          continueOnError: 'false'

        # Publish code coverage, test results and artifacts
        - template: .publish.yml

- stage: ubuntu_build
  displayName: Ubuntu
  jobs:
    - job: build_agent
      displayName: Ubuntu Agent
      pool:
        vmImage: ubuntu-16.04

      steps:
        # Download dotnet installer
        - bash: curl -Lsfo ./.dotnet/dotnet-install.sh https://dot.net/v1/dotnet-install.sh
          displayName: 'Download dotnet installer into ./dotnet'

        # Install dotnet target version
        - bash: |
            chmod +x ./.dotnet/build.sh
            ./.dotnet/dotnet-install.sh -Channel Current -Version 2.2.103
          displayName: Install target dotnet -Version
          continueOnError: 'false'

        # Install Cake.Tool dotnet tool
        - bash: dotnet tool install --global Cake.Tool --version 0.33.0
          displayName: 'Install dotnet Cake.Tool on global path'
          continueOnError: 'false'

        # Clean and checkout
        - checkout: self
          clean: all
          continueOnError: 'false'

        # Build, test and generate artifact output
        - bash: dotnet cake build.cake
          displayName: 'Build, test and generate artifact output on working directory'
          continueOnError: 'false'

        # Publish code coverage, test results and artifacts
        - template: .publish.yml
