name: hello-cake

variables:
  artifactsRootDir: $(System.DefaultWorkingDirectory)/.artifacts

trigger:
  branches:
    include:
      - master
      - preview/*
      - stable/*

jobs:

  - job: build_windows_agent
    displayName: Windows Agent
    pool:
      vmImage: vs2017-win2016

    steps:
      - template: azure-devops.template.yml

  - job: build_ubuntu_agent
    displayName: Ubuntu Agent
    pool:
      vmImage: ubuntu-16.04

    steps:
      - bash: dotnet tool install --global Cake.Tool --version 0.33.0
      - template: azure-devops.template.yml

