name: hello-cake-meetup

variables:
  artifactsRootDir: $(System.DefaultWorkingDirectory)/.artifacts

trigger:
  branches:
    include:
      - master
      - preview/*
      - stable/*



stages:
- stage: windows_build    
  jobs:
    - job: build_windows_agent
      displayName: Windows Agent
      pool:
        vmImage: vs2017-win2016

      steps:
        - template: azure-devops.template.yml

- stage: ubuntu_build
  jobs:
    - job: build_ubuntu_agent
      displayName: Ubuntu Agent
      pool:
        vmImage: ubuntu-16.04

      steps:
        - bash: dotnet tool install --global Cake.Tool --version 0.33.0
          displayName: Install dotnet Cake.Tool
        - template: azure-devops.template.yml
